[package]
name = "styxc_parser"
version = "0.0.0"
authors = ["SkyezerFox <actuallyori@gmail.com>"]
edition = "2018"

[dependencies.styxc_ast]
path = "../styxc_ast"

[dependencies.styxc_lexer]
path = "../styxc_lexer"
