[workspace]
members = [
	"fluxc_ast_passes",
	"fluxc_errors",
	"fluxc_hir",
	"fluxc_span",
	"fluxc_tests",
	"fluxc_walker",
    "fluxc_ast",
    "fluxc_codegen",
    "fluxc_parser",
    "fluxc_types",
    "fluxc"
]
