name: Run compiler Cargo tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - fluxc
          - fluxc_ast
          - fluxc_codegen
          - fluxc_errors
          - fluxc_hir
          - fluxc_main
          - fluxc_parser
          - fluxc_span
          - fluxc_tests
          - fluxc_types
          - fluxc_walker
    steps:
      - uses: actions/checkout@v2
      - name: Run crate tests
        working-directory: compiler/${{ matrix.dir }}
        run: cargo test --verbose
