name: Analyze with Clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  rust-clippy-analyze:
    name: Clippy Analysis with Reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - name: Setup cache
        uses: Swatinem/rust-cache@v1
      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest 
      - name: Install clippy-reviewdog-filter
        run: cargo install --git https://github.com/qnighy/clippy-reviewdog-filter.git
      - name: Run Clippy and pipe to Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd compiler && cargo clippy --message-format json 2>&1 | clippy-reviewdog-filter | reviewdog -reporter=github-pr-review -f=checkstyle -diff="git diff FETCH_HEAD"
