name: Codecov CI
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@master
      - name: Generate code coverage
        run: cd compiler && cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --ignore-panics
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
